### ISSUE TITLE
easy translation - compatibility with "CodeStyling Localization"

### ISSUE THREAD

**Issue by w3b-beweb** [hunk/Magic-Fields#100]
Not really a bug, just a very little code modification to make your plugin compatible with  "CodeStyling Localization" (http://wordpress.org/extend/plugins/codestyling-localization/).

Just modify line 77 in Main.php from:

load_plugin_textdomain($mf_domain, '/'.PLUGINDIR.'/'.dirname(plugin_basename(__FILE__)).'/lang', basename(dirname(__FILE__)).'/lang');

to:

load_plugin_textdomain('magic_fields', '/'.PLUGINDIR.'/'.dirname(plugin_basename(__FILE__)).'/lang', basename(dirname(__FILE__)).'/lang');

(use the domain name string value instead of the variable in the load_plugin_textdomain function call)

This way "CodeStyling Localization" can recognize eventually created po/mo pairs and users can add o update translations in a cool and intuitive way. I think this should increase not only MF translation availability, but MF diffusion also.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
