### ISSUE TITLE
'Save Order' button deletes group names

### ISSUE THREAD

**Issue by simweb** [hunk/Magic-Fields#103]
Every hit of this button deletes one panel's name from view-custom-write-panel. IDs and fields stay intact, though. In addition, an empty default group called 'Magic Fields' shows up in the editor.

As a consequence, these nameless groups do not show up in the post editor.
Very annoying.

Used: WP 3.0.3 with MF 1.5.2 (and if of interest: 7 groups in this panel)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
