### ISSUE TITLE
MF does not respect WP Plugin and Content Dirs

### ISSUE THREAD

**Issue by wunderbar** [hunk/Magic-Fields#104]
WordPress allows users to define alternate directories (and URIs) for the wp-content and plugin directories.

Currently, MF hardcodes these values along with the WP network dir ("blog.dir") which are all configurable in WP. As such, MF breaks when a user changes these locations in the WP config file.

Instead, MF should be using site_url() and plugins_url() hooks to generate links in combination with the DIRECTORY_SEPARATOR defined var.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
