### ISSUE TITLE
MacOS - tinyMCEPreInit is undefined

### ISSUE THREAD

**Issue by doublesharp** [hunk/Magic-Fields#105]
This was pre-existing in earlier version and continues to be a problem in 1.5. In both Firefox and Chrome on MacOS, I get an error that "tinyMCEPreInit is undefined" on line 1134 of groups.js. We are not using an multi-line text fields, however adding one does not cause the error to go away, and one side effect is that the file upload is not available for images (just the URL upload). 

To get past the bug, I added the following to line 1133 in groups.js: 
if (typeof tinyMCEPreInit=="undefined") return;

I do not get a rich text editor when choosing multiline, however it is availabe in the default wordpress content area.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
