### ISSUE TITLE
Bug: Shortcodes added with buttons in multiline text field are added to main WP text field

### ISSUE THREAD

**Issue by EivindFS** [hunk/Magic-Fields#107]
Hey,

With plugins such as Next Gen Gallery, the relevant button is (fortunately) displayed also in the multiline text field interface. However, when it is added, the resulting short code ends up in the main WP TinyMCE field and not the multiline text field where it was added.

This is a bug that should be fixed.

Cheers,
Eivind

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
