### ISSUE TITLE
Can't delete first group member even when others have been created

### ISSUE THREAD

**Issue by EivindFS** [hunk/Magic-Fields#108]
Hey,

There seems to be some mechanism in place that prevents me from deleting the first instance of a group. That makes perfect sense. But when a new group instance has been created, the original instance should be unlocked for deletion. As it is now, the original instance can never be deleted. I consider that a bug.

Thanks!
Eivind

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
