### ISSUE TITLE
Javascript issues

### ISSUE THREAD

**Issue by goliatone** [hunk/Magic-Fields#11]
Javascript does not work in panels created through Magic Fields.

It seems like some of the javascript scripts that should be included inside the new-post.php is not being added.

Wordpress 2.8.2., Magic Fields Version 1.3.1 to generate custom write panels.
Then I have WPML 1.7.1 and Akismet 2.2.7 in the live. No other plugins.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
