### ISSUE TITLE
Ability to nest groups (groups within groups)

### ISSUE THREAD

**Issue by thirdboxcar** [hunk/Magic-Fields#113]
I would find it useful if I could create duplicatable groups within groups. A real-world example:

- Write Panel Name: Menus (e.g., "Breakfast")
  - Group: Sub Menu (e.g., "Pancakes") (can be duplicated to create categories like "Waffles" or "Scrambles")
    - Group: Menu Item (can be duplicated)
       - Field: Title (e.g., "Blueberry") 
       - Field: Price (e.g., "$8.95")
       - Field: Description (e.g., "Stack of blueberry pancakes with whipped cream and a selection of fresh fruit on the side")

This would make Magic Fields the most magical plugin ever!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
