### ISSUE TITLE
Write Panels should be unique to each site in a WP Network installation (not shared)

### ISSUE THREAD

**Issue by figureone** [hunk/Magic-Fields#115]
This is an extension to bug 64 and 37:
https://github.com/hunk/Magic-Fields/issues/closed#issue/64
https://github.com/hunk/Magic-Fields/issues/closed#issue/37

Summary: On a WordPress Multisite build (WP Network), all sites on the network refer to one set of write panels and fields (the ones in wp_mf_write_panels, wp_mf_custom_field_properties, etc.).
Correct behavior should be a set of write panels and fields unique to each individual site (for example, in the tables wp_2_mf_write_panels, wp_2_mf_custom_field_properties).
The newest version of magic fields successfully creates the magic field tables for each new site in the network (wp_X_mf_*, where X is the id of the new site). But only wp_X_mf_post_meta and wp_X_mf_posttypes_taxonomies are getting used. All other mf table references point back to the wp_mf_* tables for the root site.

I think the offending code is in MF_Constant.php, lines 28-34:
	if(isset($current_blog)){
		$mf_prefix=$wpdb->base_prefix;
	}else{
		$mf_prefix=$wpdb->prefix;
	}

I'm not sure what the conditional is for, but on a Multisite build (WP Network), isset($current_blog) evaluates to 1/TRUE, but $current_blog is undefined. This causes $mf_prefix to get set to base_prefix (i.e., "wp_" instead of what it should be, e.g., "wp_2_").

It seems like everything would be fixed if the entire conditional above gets replaced with:
	$mf_prefix=$wpdb->prefix;

But I may be missing something. I do notice that lines 56 and 58 of MF_Constant.php don't use $mf_prefix, which suggests a partial fix is in place?
Please fill me in on the history of what's going on here--I have a set of university online courses waiting to go live because of this issue.
Thanks all!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
