### ISSUE TITLE
Multiline Textboxes Not Saving Contents

### ISSUE THREAD

**Issue by JeremyTolbert** [hunk/Magic-Fields#116]
I am using Wordpress 3.1.  My version of Magic Fields is 1.5.4. 

I have a custom write panel which utilizes a group of multiline text boxes with the visual editor enabled.  If I enter content in these and save the post, the "group" of fields collapses again when the post reloads.  When I expand the group again, the fields are empty as if the contents were not saved.  

If I change the field to disable the visual editor, the contents of the field are saved.

Any thoughts or suggestions here?  Can anyone else replicate this?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
