### ISSUE TITLE
Wordpress' autosave causes multiple problems 

### ISSUE THREAD

**Issue by michapixel** [hunk/Magic-Fields#119]
When you have some fields marked as required and an autosave is triggered, it seems the attribute 'write panel' doesn't get saved in that process. that can even cause more confusion if you hide these posts under regular Posts-Menu.

Hope you can reproduce/address this issue. i need autosave for a client, so turning it permanently off is not a solution for me.

Can't live without MF nowadays. I'd like to see this implemented in the Core though, cause i need a future-proof MF, hope you understand this ;-)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
