### ISSUE TITLE
Database doesn't get updated

### ISSUE THREAD

**Issue by TrabacchinLuigi** [hunk/Magic-Fields#121]
I've noticed trying the master branch that the database doesn't get updated if you don't activate the plugin in the MAIN website of the WP-MU network.
Probably we need to add some more hooks like "network activate" or "activate on a sub site" ...
Or maybe just check the db version at every single use of the plug-in!

I think this should be considered one major issue!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
