### ISSUE TITLE
Don't accept post if image size does not match the minimum size set on the settings

### ISSUE THREAD

**Issue by Maccoutinho** [hunk/Magic-Fields#122]
Hello,

I'm working with a very strict layout and I'd like to limit the ability of my users to post entries whose image doesn't match the minimum required size I've set on the settings.

Is there some way to display an error message if their image doesn't have that minimum size so that they're forced to find decent quality images?

Thank you very much!

MACC

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
