### ISSUE TITLE
Map type fields

### ISSUE THREAD

**Issue by TrabacchinLuigi** [hunk/Magic-Fields#126]
I'd like to create some __map__ fields because i will need them for some of my new projects, and i think it will be easier and usefull to extend this plug-in instead of creating a new one.

I was thinking about creating several new field type like ___map point___, ___map lines___, ___map roads___ and obviusly i was thinking of doing that with the google maps API v3.

I'd like to know what you think just to start with some directions, because i'd like this to be implemented in the MF!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
