### ISSUE TITLE
Have get_image() output the native alt tag of a media library image

### ISSUE THREAD

**Issue by Dermotholmes** [hunk/Magic-Fields#127]
Feature request.
Related to an image field using upload media.

Assumptions:
When using a magic-field 'media image field'

Would be great to have the get_image() function, when $tag_img=1, also output the alt tag that is entered in wordpress's native media library for that image.

Cheers

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
