### ISSUE TITLE
Manage List showing pages twice

### ISSUE THREAD

**Issue by thommeredith** [hunk/Magic-Fields#128]
Clicking on manage shows the list of magic fields pages, on two sites I have been using MF with I am getting a list with MF pages shown twice. I have cleared out all revisions and checked the database and do not see any duplicates.

I am using WP 3.1.3

I am noticing this for only some write panels, not all, hope you can replicate to troubleshoot.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
