### ISSUE TITLE
File name removal issue on upload

### ISSUE THREAD

**Issue by jbutzer** [hunk/Magic-Fields#131]
I got an issue with the "file" custom field.
It renames the chosen files during upload in the following way:
- The original name of the file gets removed completely
- A 2 digit number is added instead

e.g.
myfile.docx -> 86.docx

The original filename displays correctly on the admin screen right after the "Succesful upload" confirmation message appears.
But when viewed in the "files_mf" directory or after reload of the admin screen, the filename has been changed to 2-digit + extension.

If I run the same install (WP 3.1.4 + MF 1.5.6) locally it works fine.
So I guess it's some kind of a server issue.

Any idea what's happening and how it can be fixed?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
