### ISSUE TITLE
MF Plus WPML not working

### ISSUE THREAD

**Issue by daretothink** [hunk/Magic-Fields#133]
I'm using Wordpress 3.1.4, WPML 2.3.3, Magic Fields 1.5.6, MF Plus 1.1.

I've checked the relevant "Keep Sync" checkboxes in "Translatable fields" but it doesn't seem to be having any effect when I choose to add a new translation of a post it doesn't keep any of what I've requested in sync and I've then got to go and upload and add to all of the Magic Fields Custom Fields for each and every language. Problem is I have 7 languages and a lot of custom fields so this could be a very time consuming process.

Really appreciate your help/thoughts on this issue and thanks in advance.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
