### ISSUE TITLE
Wordpress Post Editor Shows Duplicate Media Buttons

### ISSUE THREAD

**Issue by mydreamtoobig** [hunk/Magic-Fields#136]
Hi

Here i experience an another issue with magic fields plugin. I did setup magic fields plugin in offline and exported the .pnl file to another wordpress blog.

After exported the .pnl file to new blog, its post editor shows duplicate media buttons as illustrated in the below screenshot. The problem which i specified does exists in local installation too. Installed magic fields plugin 1.5.8 in fresh wordpress installation with no other plugins.

http://i.imgur.com/ZEKzr.jpg and here is the code http://pastebin.com/hJqDHUbv

Please help me to resolve the same. (Note : Also i have sent you .pnl file to your email, Please help me to resolve the same)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
