### ISSUE TITLE
Magic fields multisite issue. Is it compatible with WP Multisite?

### ISSUE THREAD

**Issue by mistergiri** [hunk/Magic-Fields#137]
I'm seeing same custom write panels in all sites.

Lets say I have a main site called X.  Lets say Y and Z are sub sites of X. 

I created a write panel in Y called "blah". I'm seeing write panel "blah" in all my subsites. 
Is it not possible to have unique write panel in each sites?

PS: Is it possible to integrate the whole write panel "blah" in my wordpress theme using some special hooks?. So my users can post their content from main site instead of using wp-admin area. Thanks.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
