### ISSUE TITLE
Magic Fields + CKEditor

### ISSUE THREAD

**Issue by yrosen** [hunk/Magic-Fields#138]
I know this has been on your to-do list for some time. I came up with a quick hack to add CKEditor support to Magic Fields. It's not complete but hopefully someone will find it useful. I'm posting it here out of lack of a better place to post it.

My edit is at: https://github.com/yrosen/CKEditor---Magic-Fields

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
