### ISSUE TITLE
Assign fields to templates.

### ISSUE THREAD

**Issue by BMo-design** [hunk/Magic-Fields#154]
Thank you very much for your nice plugin. There is one last feature I miss. Do you know the plugin "Advanced Custom Fields"? Your plugin is much more better, than "Advanced Custom Fields". But ACF has one great advantage. I can map the fields to templates. This last feature I miss to make wordpress an ultimate CMS.

Example: If you need only at the front-page some custom fields. Here It make no sense to at a custom post type.

Thank you very much
BMo

If you want, you can contact me at: http://bmo-design.de/kontakt/

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
