### ISSUE TITLE
Can't use "Duplicate Post" plugin

### ISSUE THREAD

**Issue by relish27** [hunk/Magic-Fields#164]
Hi,

I found someone else with the same issue here: http://wordpress.org/support/topic/plugin-duplicate-post-magic-fields?replies=4

I describe my issue there, too:

....................
My Magic Fields write panel has two groups -- one containing regular fields and the other being a group of fields that can be duplicated (so you can "Add another" and a whole new set of the same fields is available).

When I use the Duplicate Post plugin, it duplicates the regular MF fields just fine. But it doesn't duplicate the multiple sets of fields from that second group. For instance, I have 7 instances of that second group of fields and I don't get any instances duplicated.
....................

Any thoughts on how to make this work?  I have a client situation where I've set up the first custom page -- and they need to set up other iterations of this same page, but with different contact info for different locations.  So it would really save them a lot of time if they didn't have to reenter the same content multiple times.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
