### ISSUE TITLE
TinyMCE not showing up after upgrade to WP 3.4 (MF 1.5.8.3)

### ISSUE THREAD

**Issue by paulcham** [hunk/Magic-Fields#165]
I did an upgrade to Wordpress 3.4 and everything seemed to be working but today I noticed all the TinyMCE editors are gone. I've done a bunch of research online but haven't been able to find anything that can fix this.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
