### ISSUE TITLE
Migrating Wordpress site and have issues getting Magic Fields to behave correctly. 

### ISSUE THREAD

**Issue by dulce303** [hunk/Magic-Fields#166]
Hello Magic Fields Team, 

I just migrated a site from WPEngine to Rackspace and I'm having trouble making MF work correctly. There is a disconnect between the JS slideshow carousel and the Background Manager plugin. 

Can someone please help me out? I can provide credentials via email. 

Cheers!
Dulce B.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
