### ISSUE TITLE
Fatal error:Call-time pass-by-reference has been removed in magic-fields\RCCWP_CustomWritePanelPage.php

### ISSUE THREAD

**Issue by mmmimmmi** [hunk/Magic-Fields#168]
Hi there.. i hope you reply to my question :)

I am using WP 3.0.1 and magic fields 1.5.1... great plugin ... 
Having some issues with php 5.4.. apparently call-time pass-by-reference has been deprecated in php5.3+ .. so now I get this error when opening my wordpress site.

I did some reading online and apparently the magic fields file RCCWP_CustomWritePanelPage.php uses call-time pass-by-reference for a couple of functions.. apparently , you will get a warning saying that "call-time pass-by-reference" is deprecated when you use & in foo(&$a);.

you can see what i mean at this link http://stackoverflow.com/questions/8971261/php-5-4-call-time-pass-by-reference-easy-fix-available 

I made some edits to the file to be compatible with php5.4 but i think i did it incorrectly because i am still getting some errors.  I think its a simple fix but i am not a programmer so I am having difficulty making the fixes correctly. If you could help I would REALLY appreciate it. Thanks..Mandy

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
