### ISSUE TITLE
How to check array exist when duplicate image

### ISSUE THREAD

**Issue by ruslyrossi** [hunk/Magic-Fields#173]
When i try to check array exist it will return this error 

Warning: array_reverse() [function.array-reverse]: The argument should be an array in /home/sritamac/public_html/wp-content/plugins/magic-fields/get-custom.php on line 306

Warning: sort() expects parameter 1 to be array, null given in /home/sritamac/public_html/wp-content/plugins/magic-fields/get-custom.php on line 307

below is my code :

<?php
//var
$images = getFieldOrder('image_gal');

if (is_array($images)) {

    foreach ($images as $image) {

        if (get('image_gal', 1, $image) == TRUE) { //check if image_gallery_image has image 
?> 

    <div id="wrap">
        <ul id="mycarousel" class="jcarousel-skin-tango">
            <?php
            $images = getFieldOrder('image_gal');
            foreach ($images as $image) { //loop image 
            ?>
            <li>
                <a class="group3"  href="<?php echo get('image_gal', 1, $image);?>">
                    <img src="<?php echo get('image_gal', 1, $image);?>" width="150" height="150" alt="" />
                </a>
            </li>  
            <?php
            }
            ?>  
        </ul>
    </div>
<?php
            break;
        }
    }
}
?>

*im using MF Version 1.5.8.1 , i think the problem maybe with getFieldOrder() .

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
