### ISSUE TITLE
Assign *only* some default categories to CPT (not custom taxonomies)

### ISSUE THREAD

**Issue by misterfulanito** [hunk/Magic-Fields#174]
Hi, i've been searching around hours with no luck, when i assign in CPT Categories > Set Default Categories (don't mind using custom taxonomies) and select some of them (e.g. Parent Category and its Child One and Child Two), all the categories in New Post are showed, is there any way to hide/exclude the others?

Thank you, guys.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
