### ISSUE TITLE
Media library URIs not encoded

### ISSUE THREAD

**Issue by gregjor** [hunk/Magic-Fields#176]
In the files MF_ImageMedia.php, RCCWP_upload_ajax.php and RCCWP_WritePostPage.php a raw URI from the WP media library is used to pass into phpThumb.php. This can cause 403 errors on some hosting configurations.

The fix is to urlencode() the URI everywhere.

MF_ImageMedia.php line 29
$image_thumb = PHPTHUMB.'?&w=150&h=120&src='.urlencode($info[0]);

RCCWP_upload_ajax.php line 165
return array('success'=>true, 'ext' => $ext, 'thumb' => PHPTHUMB.'?&w=150&h=120&src='.urlencode($uri), 'file' => $filename. '.' . $ext ,'uri' => $uri);

RCCWP_WritePostPage.php line 1715
$value  = $path.urlencode($path_image_media)."&w=150&h=120&zc=1";

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
