### ISSUE TITLE
Picture upload is not working on version 1.6.1 with Wordpress 3.6

### ISSUE THREAD

**Issue by motionfm** [hunk/Magic-Fields#177]
Picture upload on magic-fields plugin 1.6.1 it doesn't work with wordpress 3.6. Can you please fix the bug? Many of the basic feature of our website is based on this plugin. 

See for example the problem here: http://www.motionfm.com/radio-shows/wednesday/
The missing images cannot be updated.

Thank you.
Motion FM

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
