### ISSUE TITLE
Maximum number of duplicate groups ??

### ISSUE THREAD

**Issue by tstefanich** [hunk/Magic-Fields#178]
A old website I worked on updated to 3.6.1 and now when I hit the duplicate group. It makes it , I can add an image. But when I click "Update"  it does not save the new group. I don't see any errors in the console. I am at a high number of duplicates.... at 93 groups. What should I do ?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
