### ISSUE TITLE
Need to add custom post types for fuctions for some reason

### ISSUE THREAD

**Issue by reaxion** [hunk/Magic-Fields#179]
Hi!

For some reason I have to add custom post types to the functions file to get MF2 to work now, this is what I use:

====================

function include_custom_post_types( $query ) { global $wp_query;
    if ( is_category() || is_tag() || is_search() || (is_archive())) {
        $post_types = array('customposttype', 'customposttype');
        $custom_post_type = get_query_var( 'post_type' );
        if ( empty( $custom_post_type ) ) $query->set( 'post_type' ,
$post_types );
    }
    return $query;
}
add_filter( 'pre_get_posts' , 'include_custom_post_types' ); 

====================

Isn't that unusual? I'm not sure if another plugin would mess this up or what? I do have the MF2 Tookkit plugin installed, but nothing changes if I disable plugins.

I will continue to use the above until something changes. Later I will re-test the plugin on a clean install of WP with only MF2 installed in order to be 100%.

I am currently running the plugin in WP 3.7.1

Thanks!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
