### ISSUE TITLE
getting javascript alert on updating MF page/post WP 3.9

### ISSUE THREAD

**Issue by mikecastrodemaria** [hunk/Magic-Fields#181]
Magic Fields 1.6.2 and 2.2.1
WP 3.9

go to edit content in the_content area. I click "Update" and I get the alert:
"The changes you made will be lost if you navigate away from this page.
Are you sure you want to leave this page?"

If you select "Leave this page" it will allow the page/post to be updated.

https://github.com/magic-fields-team/Magic-Fields-2/issues/224

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
