### ISSUE TITLE
Warning:  Creating default object from empty value in RCCWP_CustomWritePanel.php on line 641

### ISSUE THREAD

**Issue by jrgarou** [hunk/Magic-Fields#183]
In version 1.6.2.1 there's a message in .pnl files:

<b>Warning</b>:  Creating default object from empty value in <b>/Users/jrgarou/Sites/mandalah-site/public/wp/wp-content/plugins/magic-fields/RCCWP_CustomWritePanel.php</b> on line <b>641</b><br />

...and when we import the file(.pnl) the Magic Field comes empty.

<b>I'm using WordPress 3.9.1</b>

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
