### ISSUE TITLE
in multiple page or post - link on Add New wrong

### ISSUE THREAD

**Issue by workshopcollective** [hunk/Magic-Fields#185]
Hello,

When you click on manage inside a tab previously created in White Panel (example : Videos)
You will have a link inside the page like this one:
Manage >> Videos "Add New" (button)
This link will redirect you to the post or page per default outside of the white panel

Otherwise the link in the tab under manage "new" is working perfectly

Let me know if you have a solution for that
Thank you

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
