### ISSUE TITLE
Image Field Error - You do not have sufficient permissions to access this page

### ISSUE THREAD

**Issue by M4CC** [hunk/Magic-Fields#186]
Hello,

All of a sudden I'm not able to upload or delete any images on new or existing posts on my website on Magic Fields.

I get the error message:
"You do not have sufficient permissions to access this page."

I have the same website running locally on XAMPPP and it works just fine so it must be something related to server configuration.

I also have other websites with Magic Fields on the same server and they are all working fine.

What do you think might be happening with this particular install?

Thank you!

**Comment by hunk** [comment]
Which version you uses?

try for MF 2.x add .htaccess in MF plugin folder

<FilesMatch "^(mf_upload)\.php$">
<IfModule !mod_authz_core.c>
Order allow,deny
Allow from all
</IfModule>
<IfModule mod_authz_core.c>
Require all granted
</IfModule>
</FilesMatch>

MF 1.x same path

<FilesMatch "(RCCWP_upload|RCCWP_GetDuplicate)\.php$">
<IfModule !mod_authz_core.c>
Order allow,deny
Allow from all
</IfModule>
<IfModule mod_authz_core.c>
Require all granted
</IfModule>
</FilesMatch>

**Comment by M4CC** [comment]
Thanks!
