### ISSUE TITLE
Authentication failed!

### ISSUE THREAD

**Issue by kensk8** [hunk/Magic-Fields#188]
In MF 1.7.2 and Wordpress 4.6 or 4.5.3, i cant access to the wp-admin i get this message only as pain text:

Authentication failed!

**Comment by kensk8** [comment]
I rollback to 1.7.1 and everything works fine

**Comment by hunk** [comment]
Hello, do you have another plugin installed?​, I tested MF 1.7.2 with WP 4.6 or 4.5.3 and everything is ok.

**Comment by kensk8** [comment]
I make a clear install of WP 4.6 and MF 1.7.2 and i get the same error, something i notice was when i activate the plugin i get the message:

> The plugin generated 1119 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Then i check the error log an get this warning messages i dont know if help:

`[Thu Sep 01 15:12:00.487165 2016] [:error] [pid 2233] [client ::1:49651] PHP Warning:  Missing argument 2 for wpdb::prepare(), called in /wordpress/wp-content/plugins/magic-fields/RCCWP_Application.php on line 91 and defined in /wordpress/wp-includes/wp-db.php on line 1275, referer: http://localhost/wordpress/wp-admin/plugins.php`

`[Thu Sep 01 15:12:00.487516 2016] [:error] [pid 2233] [client ::1:49651] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'wp_ilo20mf_post_meta' at line 1 for query SHOW TABLES LIKE wp_ilo20mf_post_meta made by activate_plugin, do_action('activate_magic-fields/Main.php'), call_user_func_array, RCCWP_Application::Install, referer: http://localhost/wordpress/wp-admin/plugins.php`

`[Thu Sep 01 15:12:00.578355 2016] [:error] [pid 2233] [client ::1:49651] PHP Warning:  Missing argument 2 for wpdb::prepare(), called in /wordpress/wp-content/plugins/magic-fields/RCCWP_Application.php on line 139 and defined in /wordpress/wp-includes/wp-db.php on line 1275, referer: http://localhost/wordpress/wp-admin/plugins.php`

`[Thu Sep 01 15:12:00.578604 2016] [:error] [pid 2233] [client ::1:49651] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'wp_ilo20mf_write_panels' at line 1 for query SHOW TABLES LIKE wp_ilo20mf_write_panels made by activate_plugin, do_action('activate_magic-fields/Main.php'), call_user_func_array, RCCWP_Application::Install, referer: http://localhost/wordpress/wp-admin/plugins.php`

`[Thu Sep 01 15:12:00.697474 2016] [:error] [pid 2233] [client ::1:49651] PHP Warning:  Missing argument 2 for wpdb::prepare(), called in /wordpress/wp-content/plugins/magic-fields/RCCWP_Application.php on line 262 and defined in /wordpress/wp-includes/wp-db.php on line 1275, referer: http://localhost/wordpress/wp-admin/plugins.php`

`[Thu Sep 01 15:12:00.697709 2016] [:error] [pid 2233] [client ::1:49651] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'wp_ilo20mf_custom_field_types' at line 1 for query SHOW TABLES LIKE wp_ilo20mf_custom_field_types made by activate_plugin, do_action('activate_magic-fields/Main.php'), call_user_func_array, RCCWP_Application::Install, RCCWP_Application::UpgradeBlog, referer: http://localhost/wordpress/wp-admin/plugins.php`

`[Thu Sep 01 15:12:00.699379 2016] [:error] [pid 2233] [client ::1:49651] PHP Warning:  Missing argument 2 for wpdb::prepare(), called in /wordpress/wp-content/plugins/magic-fields/RCCWP_Application.php on line 273 and defined in /wordpress/wp-includes/wp-db.php on line 1275, referer: http://localhost/wordpress/wp-admin/plugins.php`

I have PHP Version 5.5.34 and MySQL 5.7.12

**Comment by hunk** [comment]
ok, thanks. this information will help me

**Comment by hunk** [comment]
one more question, when you have the "Authentication failed" message, what role user do you have?

**Comment by hunk** [comment]
Hello, I created a new branch with all changes for fix this (the messages error and the warnings) can you test this version https://github.com/hunk/Magic-Fields/tree/v1_7_3

**Comment by kensk8** [comment]
I test the branch and now works great, no errors and the Authentication failed! doesn't appear, thanks so much!, only to clarify the error appear when you are logged out and go to the example: localhost/wp-admin that URL show the error, was a blank page and that text only. But whit this branch the error now does not appear, thanks again.
