### ISSUE TITLE
Wrong logical expression in `rccwp_processor.php`

### ISSUE THREAD

**Issue by Uriziel01** [hunk/Magic-Fields#191]
In commit `b26965a477d939f3520ba76dfb04a5d5187ce990` there was a bug introduced in file `rccwp_processor.php` on lines:
```
if (
	!( is_user_logged_in() &&
		(current_user_can('edit_posts') || current_user_can('edit_published_pages'))
		)
	) {
	die(__("Authentication failed!",$mf_domain));
})
```
If the user is not logged in both of these conditions will return false resulting in true statement and lock of `wp-admin` access, I had to resolve this issue for one of my clients because he was unable to login to admin pages.
Sorry for no pull request but I really don't have much time right now.

**Comment by hunk** [comment]
Hello, yes sorry for the delay in merge this change, I fixed this several weeks ago https://github.com/hunk/Magic-Fields/commit/8a622427d1fa660d0f81d1bd0b2a2b181006727c#diff-c651583dbe7ee50b9e91904ab2886968 , I want to check another pull request and release a new version.
