### ISSUE TITLE
Solution for insert image field

### ISSUE THREAD

**Issue by evoratec** [hunk/Magic-Fields#193]
In line 34 of MF_ImageMedia.php change for:

$data = array('success'=>true,'image' => $image_thumb,'field_id' => $field_id,'image_value' => $image_id);

**Comment by hunk** [comment]
thanks https://github.com/hunk/Magic-Fields/commit/da1e2dbf6bce71908e145d93b360400fa72dc014

**Comment by evoratec** [comment]
De nada.
