### ISSUE TITLE
 'Set image in field' link does not work from Gallery tab

### ISSUE THREAD

**Issue by MRVerv** [hunk/Magic-Fields#194]
On a website for which we have recently taken over support, the media-upload dialog has a Gallery tab. The 'Set image in field' link worked from the Media Library tab (after several updates and patches), but not from the 'Gallery' tab. It gave an error about a missing nonce_ajax_get_image_media_info.

I fixed this by editing Main.php::charge_link_after_upload_image() and replacing the test
  $_REQUEST['tab'] == 'library'
by
  ($_REQUEST['tab'] == 'library' || $_REQUEST['tab'] == 'gallery')
This solved the problem.

**Comment by hunk** [comment]
Merge https://github.com/hunk/Magic-Fields/commit/1cc7516a9a19de7bce573a6b03722a659c90bb50 thanks
