### ISSUE TITLE
Page template setting not saved creating a Page Write Panel

### ISSUE THREAD

**Issue by w3b-beweb** [hunk/Magic-Fields#28]
If you create a new write panel of Page type and select a page template different from the default page template, the plugin doesn't save this setting. You have to set the template for each istance of this write panel through the standard wordpress page interface.

Wordpress 2.9.2

Magic-Fields 1.4
qTranslate 2.5.7
qTranslate META 0.8.3
Google XML Sitemaps with qTranslate Support  3.1.6.3
TinyMCE Advanced 3.2.7
TinyMCE Excerpt 1.33

Php 5.2.4
Mysql 5.0.51a

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
