### ISSUE TITLE
Created Pages are not Inside Correct Write Panel

### ISSUE THREAD

**Issue by nukecpower** [hunk/Magic-Fields#58]
I think this problem already exist since It was named Flutter.
When A Page created using write panel’s “Add New” , It goes into “Pages” instead of the certain Write Panel.
Yes, I see the custom-write-panel-id=X variable in the URL, but still the problem occurred.

Any idea to fix the problem permanently?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
