### ISSUE TITLE
Storage Quota in Wordpress Multisite

### ISSUE THREAD

**Issue by caudurow3** [hunk/Magic-Fields#59]
Hi,
I have a strange bug in calculating storage space for blogs in Multisite. Using Magic Fields all files that are uploaded directly (not though media uploader) are stored in /blogs.dir/files_mf/

The storage quota function apparently only calculates the size of files inside a folder in the same directory  /blogs.dir/files/ 

This makes it so that it never adds up any of the magic field files upload - a fix for this could be to put the magic field files inside the  /blogs.dir/files/ folder such as  /blogs.dir/files/files_mf/

Thanks

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
