### ISSUE TITLE
v1.5RC1: Drop down with set initial value shows as (not selected) in collapsed form

### ISSUE THREAD

**Issue by arafalov** [hunk/Magic-Fields#66]
In v1.5RC1, if I have a drop down field with set initial value, the 'New' page shows the field as '(not selected)', even though obviously the initial value is the one that's set. After the draft is saved, it shows correctly.

Would be nice for those default values to be displayed.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
