### ISSUE TITLE
v1.5RC1: Internet Explorer 7 shows a broken item on Admin menu

### ISSUE THREAD

**Issue by arafalov** [hunk/Magic-Fields#67]
In IE 7.0.5730.11, the 'Magic Fields' top level menu in admin interface has a broken image indicator to the left of 'Magic Fields' text. In FireFox, there seem to be empty space instead. 

There is no icon similar to the other menu icons. There is no icon in collapsed menu mode either.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
