### ISSUE TITLE
Custom Post draft is saved as normal Post draft if mf custom fields are missing

### ISSUE THREAD

**Issue by conualfy** [hunk/Magic-Fields#68]
I found this bug in the previous stable version and tested it in this beta to see if it still is here.

If one does not save any custom fields or if one has mandatory fields and does not initialize any of them and hits Save as Draft, wp saves the draft as a normal post draft.
In the case of missing mandatory fields it should not save it at all and just point to the fields not completed.

I guess the solution is either to create mf also for drafts, or block the draft creation.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
