### ISSUE TITLE
International Date Format

### ISSUE THREAD

**Issue by M-O-Z-G** [hunk/Magic-Fields#69]
Default date parse from Database in English.
Nessasary replace in string №205 of get-custom.php

$fieldValue = date($fieldProperties['format'],strtotime($fieldValue)); 
to
$fieldValue = date_i18n($fieldProperties['format'],strtotime($fieldValue)); 

Now date display in blog with standart locale of Wordpress.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
