### ISSUE TITLE
Campos Textbox en el admin se muestran con un size igual a su tamaño

### ISSUE THREAD

**Issue by Jemact** [hunk/Magic-Fields#70]
Campos Textbox de un tamaño grande en el admin se crean con un size de ese tamaño descuadrandose completamente.

Ejemplo si creo uno con un tamaño de 255 maximo de caracteres me creara en el admin un campo texto con maxlength="255" y con size="255"

Gracias por el magnifico plugin que habeis creado

Un saludo

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
