### ISSUE TITLE
Initial issues after upgrading from MF 1.4.5 to 1.5

### ISSUE THREAD

**Issue by aproimage** [hunk/Magic-Fields#71]
After upgrading from Magic Fields 1.4.5 to 1.5 I have come across a few problems.

Firstly, it appears that Page Attributes no longer display in the edit page area, I have tried changing the write panel settings using Magic Fields to toggle page attributes on and off for given fields but still nothing displays.

The 'Set Page Template' and 'Set Page parent' buttons under Magic Fields Attributes also appear to do nothing for me.

Another problem has been that when creating a new field I cannot add a Main Page i.e. a page with no parent, magic Fields seems to automatically assign a random parent page to new pages that are created.

I am currently running Wordpress version 3.0.1

Regards,

Rob

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
