### ISSUE TITLE
Cannot fully translate the plugin

### ISSUE THREAD

**Issue by conualfy** [hunk/Magic-Fields#72]
Even if the admin interface is not fully translated, the one a normal user (the one posting a custom post) sees should.

The problem is that unless editing the source php and js files one cannot fully translate the plugin.

Files I had to modify for normal texts or javascript confirmations/errors:
RCCWP_CustomWritePanelPage.php
RCCWP_WritePostPage.php
js/groups.js
js/custom_fields/validate.js

There might be more, these are the ones that I found.

MF: 1.5, 1.5.1

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
