### ISSUE TITLE
Sanitized field/group name is not sanitizing extended character sets

### ISSUE THREAD

**Issue by conualfy** [hunk/Magic-Fields#73]
Characters like şŞ ţŢ ăĂ îÎ âÂ șȘ țȚ are not sanitized correctly in the fields where MF should propose those names. It only replaces spaces and applies lowercase, but these characters remain there.

It is probably one should want with those characters to be seen in public places, but not in variable names.

MF 1.5.1

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
