### ISSUE TITLE
Ability to specify toolbar options for the TinyMCE editor

### ISSUE THREAD

**Issue by ShadowXVII** [hunk/Magic-Fields#76]
Either through a per-field setting, or universally using something like the TinyMCE Options Override plug-in.

Should be able to customize using [the TinyMCE reference wiki](http://wiki.moxiecode.com/index.php/TinyMCE:Configuration/theme_advanced_buttons_1_n).

wp_tiny_mce() can accept the above 'init' settings [as per here](http://www.keighl.com/2010/01/tinymce-in-wordpress-plugins/).

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
