### ISSUE TITLE
1.5.1 Installation fails on brand new WP3.0.1 

### ISSUE THREAD

**Issue by cannycookie** [hunk/Magic-Fields#94]
Upgrade to 1.5.1 failed and broke WP.  Uninstall failed.  Starting with a new WP installation following message is received during Magic Fields install:-

Downloading install package from http://downloads.wordpress.org/plugin/magic-fields.1.5.1.zip…

Unpacking the package…

Installing the plugin…

Could not copy file. /public_html/eko/wordpress/wp-content/plugins/magic-fields/images/mf-t-radiobutton-list.png

Plugin install failed.

Actions: Return to Plugin Installer

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
