### ISSUE TITLE
CAN'T ADD NEW POST ANYMORE

### ISSUE THREAD

**Issue by rccc** [hunk/Magic-Fields#95]
Hello,

Look at this http://vimeo.com/16360936 ( !!! video duration is 1mn and not 8mn as indicated !!! ).

I created an issue here one month ago, and this issue has disappeared also the bug is always occuring ( thank you very much to the person who  deleted it ...  ). 

i already said i resolved the issue by checking/unchecking and checking/ unchecking again all magic fields options,  furthermore, the 'Default Panel' have to be set to 'none'.

this plugin is couls be really great but PLEASE stop further development and fix all the bugs first.

thanks for reading ( and for response if any developpers read it )

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
